# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52425189b8b6fc85801bea816263c107d6a0c9720fc3f01ce2d790b6c079395a366028fbd153f119d73eca97233086c632ff7fc61909f1d4ac2b957b6e704282

test:
  secret_key_base: 4dfa73c457ffb15d9bbae4069f9015d47259fa0968de4652d63aad458e09318ffe5a148833bc897f33c4bd8e45c565ec6df5a051015511f2cd12825e411a6089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
